function dl_Arm_Bottom = FRD_Dl_Arm_Bottom(dl_Beta_Hand,dl_Alpha_Hand,l_Alpha_Hand,l_Beta_Hand,length_Hand)
%FRD_DL_ARM_BOTTOM
%    DL_ARM_BOTTOM = FRD_DL_ARM_BOTTOM(DL_BETA_HAND,DL_ALPHA_HAND,L_ALPHA_HAND,L_BETA_HAND,LENGTH_HAND)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    11-Jun-2021 23:41:15

t2 = cos(l_Alpha_Hand);
t3 = cos(l_Beta_Hand);
t4 = sin(l_Alpha_Hand);
t5 = sin(l_Beta_Hand);
dl_Arm_Bottom = [dl_Beta_Hand.*length_Hand.*t3,-dl_Beta_Hand.*length_Hand.*t2.*t5-dl_Alpha_Hand.*length_Hand.*t3.*t4,-dl_Beta_Hand.*length_Hand.*t4.*t5+dl_Alpha_Hand.*length_Hand.*t2.*t3];
