function dr_Shoulder = FRD_Dr_Shoulder(alpha_Body,beta_Body,dalpha_Body,dbeta_Body,dgamma_Body,dx_Head,dy_Head,dz_Head,gamma_Body,width_Body)
%FRD_DR_SHOULDER
%    DR_SHOULDER = FRD_DR_SHOULDER(ALPHA_BODY,BETA_BODY,DALPHA_BODY,DBETA_BODY,DGAMMA_BODY,DX_HEAD,DY_HEAD,DZ_HEAD,GAMMA_BODY,WIDTH_BODY)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    17-Jun-2021 17:18:06

t2 = cos(alpha_Body);
t3 = cos(beta_Body);
t4 = cos(gamma_Body);
t5 = sin(alpha_Body);
t6 = sin(beta_Body);
t7 = sin(gamma_Body);
dr_Shoulder = [dx_Head-(dbeta_Body.*t4.*t6.*width_Body)./2.0-(dgamma_Body.*t3.*t7.*width_Body)./2.0,dy_Head+(width_Body.*(dalpha_Body.*t2.*t6+dbeta_Body.*t3.*t5-dalpha_Body.*t3.*t5.*t7-dbeta_Body.*t2.*t6.*t7+dgamma_Body.*t2.*t3.*t4))./2.0,dz_Head+(width_Body.*(dalpha_Body.*t5.*t6-dbeta_Body.*t2.*t3+dalpha_Body.*t2.*t3.*t7-dbeta_Body.*t5.*t6.*t7+dgamma_Body.*t3.*t4.*t5))./2.0];
