function dr_Arm_Bottom = FRD_Dr_Arm_Bottom(dr_Beta_Hand,dr_Alpha_Hand,length_Hand,r_Alpha_Hand,r_Beta_Hand)
%FRD_DR_ARM_BOTTOM
%    DR_ARM_BOTTOM = FRD_DR_ARM_BOTTOM(DR_BETA_HAND,DR_ALPHA_HAND,LENGTH_HAND,R_ALPHA_HAND,R_BETA_HAND)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    17-Jun-2021 17:17:09

t2 = cos(r_Alpha_Hand);
t3 = cos(r_Beta_Hand);
t4 = sin(r_Alpha_Hand);
t5 = sin(r_Beta_Hand);
dr_Arm_Bottom = [-dr_Beta_Hand.*length_Hand.*t3,-dr_Beta_Hand.*length_Hand.*t2.*t5-dr_Alpha_Hand.*length_Hand.*t3.*t4,-dr_Beta_Hand.*length_Hand.*t4.*t5+dr_Alpha_Hand.*length_Hand.*t2.*t3];
