function [ddx_Head,ddy_Head,ddz_Head,r_Tau_Alpha_Shoulder] = HFD_Dds_Body_Alpha(alpha_Body,dalpha_Body,ddalpha_Body,depth_Body,g,height_Body,l_Beta_Hand,l_F_X,l_F_Y,l_F_Z,l_Tau_Gamma_Shoulder,m_Body,r_Beta_Hand,r_F_X,r_F_Y,r_F_Z,r_Tau_Gamma_Shoulder)
%HFD_DDS_BODY_ALPHA
%    [DDX_HEAD,DDY_HEAD,DDZ_HEAD,R_TAU_ALPHA_SHOULDER] = HFD_DDS_BODY_ALPHA(ALPHA_BODY,DALPHA_BODY,DDALPHA_BODY,DEPTH_BODY,G,HEIGHT_BODY,L_BETA_HAND,L_F_X,L_F_Y,L_F_Z,L_TAU_GAMMA_SHOULDER,M_BODY,R_BETA_HAND,R_F_X,R_F_Y,R_F_Z,R_TAU_GAMMA_SHOULDER)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    18-Jun-2021 23:47:49

t2 = cos(alpha_Body);
t3 = sin(alpha_Body);
t4 = sin(l_Beta_Hand);
t5 = sin(r_Beta_Hand);
t6 = g.*m_Body;
t7 = dalpha_Body.^2;
t8 = depth_Body.^2;
t9 = height_Body.^2;
t14 = 1.0./m_Body;
ddx_Head = t14.*(l_F_X+r_F_X);
if nargout > 1
    t10 = t2.^2;
    t12 = t3.^2;
    t15 = -t6;
    t16 = ddalpha_Body.*height_Body.*t3.*2.0;
    t17 = height_Body.*t2.*t7.*2.0;
    t18 = (ddalpha_Body.*height_Body.*m_Body.*t2)./2.0;
    t20 = (height_Body.*m_Body.*t3.*t7)./2.0;
    t11 = t10.^2;
    t13 = t12.^2;
    t19 = -t18;
    t21 = t16+t17;
    t22 = (m_Body.*t21)./4.0;
    t24 = l_F_Z+r_F_Z+t15+t19+t20;
    t23 = l_F_Y+r_F_Y+t22;
    ddy_Head = t14.*t23;
end
if nargout > 2
    ddz_Head = t14.*t24;
end
if nargout > 3
    r_Tau_Alpha_Shoulder = (l_Tau_Gamma_Shoulder.*t4.*t10+l_Tau_Gamma_Shoulder.*t4.*t12+r_Tau_Gamma_Shoulder.*t5.*t10+r_Tau_Gamma_Shoulder.*t5.*t12)./(t10.*2.0+t12.*2.0)+(height_Body.*t2.*t6)./4.0+(height_Body.*t2.*t24)./4.0-(height_Body.*t3.*t23)./4.0+(ddalpha_Body.*m_Body.*t8.*t11)./2.4e+1+(ddalpha_Body.*m_Body.*t9.*t10)./8.0+(ddalpha_Body.*m_Body.*t9.*t11)./2.4e+1+(ddalpha_Body.*m_Body.*t8.*t13)./2.4e+1+(ddalpha_Body.*m_Body.*t9.*t12)./8.0+(ddalpha_Body.*m_Body.*t9.*t13)./2.4e+1+(ddalpha_Body.*m_Body.*t8.*t10.*t12)./1.2e+1+(ddalpha_Body.*m_Body.*t9.*t10.*t12)./1.2e+1;
end
