function [A11,A12,A13,A14,A15,A16] = HFD_Coeffs_Ddl_Shoulder_Force_Row1(m_Body)
%HFD_COEFFS_DDL_SHOULDER_FORCE_ROW1
%    [A11,A12,A13,A14,A15,A16] = HFD_COEFFS_DDL_SHOULDER_FORCE_ROW1(M_BODY)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    15-Jun-2021 15:20:51

t2 = 1.0./m_Body;
A11 = t2;
if nargout > 1
    A12 = 0.0;
end
if nargout > 2
    A13 = 0.0;
end
if nargout > 3
    A14 = t2;
end
if nargout > 4
    A15 = 0.0;
end
if nargout > 5
    A16 = 0.0;
end
