function [A11,A12,A13,A14,A15,A16,A21,A22,A23,A24,A25,A26,A31,A32,A33,A34,A35,A36] = HFD_Coeffs_Ddr_Shoulder_Force(alpha_Body,beta_Body,depth_Body,gamma_Body,height_Body,m_Body,width_Body)
%HFD_COEFFS_DDR_SHOULDER_FORCE
%    [A11,A12,A13,A14,A15,A16,A21,A22,A23,A24,A25,A26,A31,A32,A33,A34,A35,A36] = HFD_COEFFS_DDR_SHOULDER_FORCE(ALPHA_BODY,BETA_BODY,DEPTH_BODY,GAMMA_BODY,HEIGHT_BODY,M_BODY,WIDTH_BODY)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    04-Jun-2021 18:16:35

t2 = cos(alpha_Body);
t3 = cos(beta_Body);
t4 = cos(gamma_Body);
t5 = sin(alpha_Body);
t6 = sin(beta_Body);
t7 = sin(gamma_Body);
t8 = depth_Body.^2;
t9 = height_Body.^2;
t11 = width_Body.^2;
t17 = 1.0./m_Body;
t10 = t9.^2;
t12 = t2.^2;
t13 = t4.^2;
t14 = t5.^2;
t15 = t6.^2;
t16 = t7.^2;
t18 = m_Body.*t8;
t19 = m_Body.*t11;
t20 = t8.*t9;
t21 = t8+t9;
t22 = t8.*t11;
t23 = t9.*t11;
t24 = t9+t11;
t26 = (t2.*t3.*width_Body)./2.0;
t27 = (t2.*t6.*width_Body)./2.0;
t28 = (t3.*t5.*width_Body)./2.0;
t29 = (t5.*t6.*width_Body)./2.0;
t37 = t2.*t6.*t7.*width_Body.*(-1.0./2.0);
t38 = t3.*t5.*t7.*width_Body.*(-1.0./2.0);
t25 = t9.*t13.*3.0;
t30 = 1.0./t21;
t31 = 1.0./t24;
t32 = t7.*t26;
t33 = t7.*t27;
t34 = t7.*t28;
t35 = t7.*t29;
t36 = t18+t19;
t39 = t2.*t5.*t10.*t13;
t40 = t2.*t5.*t10.*t16;
t41 = t10.*t12.*t13.*3.0;
t42 = t10.*t12.*t16.*3.0;
t43 = t10.*t13.*t14.*3.0;
t44 = t10.*t14.*t16.*3.0;
t47 = t2.*t5.*t16.*t20;
t48 = t2.*t5.*t13.*t23;
t49 = t12.*t16.*t20.*3.0;
t50 = t12.*t13.*t23.*3.0;
t52 = t14.*t16.*t20.*3.0;
t53 = t13.*t14.*t23.*3.0;
t63 = t27+t38;
t64 = t28+t37;
t73 = t10+t20+t22+t23;
t45 = 1.0./t36;
t46 = -t40;
t51 = t24+t25;
t54 = -t47;
t55 = height_Body.*t4.*t17.*t31.*6.0;
t56 = t26+t35;
t57 = t29+t32;
t58 = height_Body.*t2.*t4.*t17.*t30.*6.0;
t59 = height_Body.*t4.*t5.*t17.*t30.*6.0;
t60 = height_Body.*t2.*t7.*t17.*t31.*6.0;
t61 = height_Body.*t5.*t7.*t17.*t31.*6.0;
t62 = t3.*t7.*t17.*t31.*width_Body.*6.0;
t68 = t2.*t3.*t4.*t17.*t31.*width_Body.*6.0;
t69 = t3.*t4.*t5.*t17.*t31.*width_Body.*6.0;
t72 = height_Body.*t3.*t4.*t7.*t17.*t31.*width_Body.*3.0;
t74 = t2.*t4.*t7.*t9.*t17.*t31.*3.0;
t75 = t4.*t5.*t7.*t9.*t17.*t31.*3.0;
t76 = height_Body.*t2.*t3.*t13.*t17.*t31.*width_Body.*3.0;
t77 = height_Body.*t2.*t3.*t16.*t17.*t31.*width_Body.*3.0;
t78 = height_Body.*t3.*t5.*t13.*t17.*t31.*width_Body.*3.0;
t79 = height_Body.*t3.*t5.*t16.*t17.*t31.*width_Body.*3.0;
t84 = 1.0./t73;
t87 = height_Body.*t2.*t3.*t4.*t5.*t7.*t17.*t31.*width_Body.*-3.0;
t92 = t17.*t30.*t63.*1.2e+1;
t118 = t41+t44+t50+t52+t73;
t119 = t42+t43+t49+t53+t73;
t65 = -t58;
t66 = -t59;
t67 = -t62;
t70 = -t68;
t71 = -t69;
t80 = t2.*t3.*t4.*t6.*t11.*t45.*3.0;
t81 = t3.*t4.*t5.*t6.*t11.*t45.*3.0;
t82 = t11.*t13.*t15.*t45.*3.0;
t83 = t14.*t72;
t85 = t2.*t5.*t72;
t86 = t12.*t72;
t88 = t2.*t4.*t7.*t11.*t15.*t45.*3.0;
t89 = t4.*t5.*t7.*t11.*t15.*t45.*3.0;
t90 = t17.*t31.*t51;
t91 = t17.*t30.*t57.*1.2e+1;
t93 = t55+t62;
t94 = t2.*t3.*t45.*t56.*width_Body.*6.0;
t95 = t3.*t5.*t45.*t56.*width_Body.*6.0;
t96 = t4.*t6.*t45.*t56.*width_Body.*6.0;
t97 = t57.*t58;
t98 = t57.*t59;
t100 = t2.*t3.*t45.*t64.*width_Body.*6.0;
t101 = t3.*t5.*t45.*t64.*width_Body.*6.0;
t102 = t4.*t6.*t45.*t64.*width_Body.*6.0;
t103 = t58.*t63;
t104 = t59.*t63;
t105 = t2.*t6.*t7.*t45.*t56.*width_Body.*6.0;
t106 = t5.*t6.*t7.*t45.*t56.*width_Body.*6.0;
t107 = t60+t68;
t108 = t2.*t6.*t7.*t45.*t64.*width_Body.*6.0;
t109 = t61+t69;
t110 = t5.*t6.*t7.*t45.*t64.*width_Body.*6.0;
t113 = t39+t46+t48+t54;
t116 = t59+t92;
t122 = t17.*t84.*t118;
t123 = t17.*t84.*t119;
t99 = t55+t67;
A11 = -t72+t82+t90-(t3.*t7.*t99.*width_Body)./2.0;
if nargout > 1
    A12 = t74+t76-t102-(t3.*t7.*t107.*width_Body)./2.0;
end
if nargout > 2
    A13 = t75+t78+t96-(t3.*t7.*t109.*width_Body)./2.0;
end
if nargout > 3
    A14 = t72-t82+t90-(t3.*t7.*t93.*width_Body)./2.0;
end
if nargout > 4
    t111 = t60+t70;
    A15 = t74-t76+t102-(t3.*t7.*t111.*width_Body)./2.0;
end
if nargout > 5
    t112 = t61+t71;
    A16 = t75-t78-t96-(t3.*t7.*t112.*width_Body)./2.0;
end
if nargout > 6
    A21 = t74-t77-t81+t88+t4.*t26.*t99;
end
if nargout > 7
    A22 = t86+t101+t104-t108+t123+t27.*t116+t38.*t116+t4.*t26.*t107;
end
if nargout > 8
    t114 = t58+t91;
    t115 = t65+t91;
    t117 = t66+t92;
    t120 = t17.*t84.*t113.*3.0;
    t121 = -t120;
    A23 = t85-t95+t98+t105+t121-t27.*(t58-t91)-t38.*(t58-t91)+t4.*t26.*t109;
end
if nargout > 9
    A24 = t74+t77+t81-t88+t4.*t26.*t93;
end
if nargout > 10
    A25 = -t101+t108+t123-t34.*(t59-t92)+t4.*t26.*t111+(t2.*t6.*width_Body.*(t59-t92))./2.0-height_Body.*t4.*t5.*t17.*t30.*t63.*6.0-height_Body.*t3.*t4.*t7.*t12.*t17.*t31.*width_Body.*3.0;
end
if nargout > 11
    A26 = t87+t95-t105+t121+t34.*t114+t4.*t26.*t112-(t2.*t6.*t114.*width_Body)./2.0-height_Body.*t4.*t5.*t17.*t30.*t57.*6.0;
end
if nargout > 12
    A31 = t75-t79+t80+t89+t4.*t28.*t99;
end
if nargout > 13
    A32 = t85-t100-t110+t121+t29.*t116+t32.*t116+t4.*t28.*t107-height_Body.*t2.*t4.*t17.*t30.*t63.*6.0;
end
if nargout > 14
    A33 = t83+t94+t106+t122-t29.*(t58-t91)-t32.*(t58-t91)+t4.*t28.*t109-height_Body.*t2.*t4.*t17.*t30.*t57.*6.0;
end
if nargout > 15
    A34 = t75+t79-t80-t89+t4.*t28.*t93;
end
if nargout > 16
    A35 = t87+t100+t103+t110+t121+t4.*t28.*t111+(t5.*t6.*width_Body.*(t59-t92))./2.0+(t2.*t3.*t7.*width_Body.*(t59-t92))./2.0;
end
if nargout > 17
    A36 = -t94+t97-t106+t122+t4.*t28.*t112-(t5.*t6.*t114.*width_Body)./2.0-(t2.*t3.*t7.*t114.*width_Body)./2.0-height_Body.*t3.*t4.*t7.*t14.*t17.*t31.*width_Body.*3.0;
end
