function [A11,A12,A21,A22,A31,A32] = HFD_Coeffs_Ddl_Shoulder_Tau_Beta(alpha_Body,beta_Body,depth_Body,gamma_Body,height_Body,l_Alpha_Hand,m_Body,r_Alpha_Hand,width_Body)
%HFD_COEFFS_DDL_SHOULDER_TAU_BETA
%    [A11,A12,A21,A22,A31,A32] = HFD_COEFFS_DDL_SHOULDER_TAU_BETA(ALPHA_BODY,BETA_BODY,DEPTH_BODY,GAMMA_BODY,HEIGHT_BODY,L_ALPHA_HAND,M_BODY,R_ALPHA_HAND,WIDTH_BODY)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    04-Jun-2021 18:16:37

t2 = cos(alpha_Body);
t3 = cos(beta_Body);
t4 = cos(gamma_Body);
t5 = cos(l_Alpha_Hand);
t6 = sin(alpha_Body);
t7 = cos(r_Alpha_Hand);
t8 = sin(beta_Body);
t9 = sin(gamma_Body);
t10 = sin(l_Alpha_Hand);
t11 = sin(r_Alpha_Hand);
t12 = depth_Body.^2;
t13 = height_Body.^2;
t14 = width_Body.^2;
t15 = 1.0./m_Body;
t16 = t6.*t10;
t17 = t6.*t11;
t18 = m_Body.*t12;
t19 = m_Body.*t14;
t20 = t2.*t5;
t21 = t2.*t7;
t22 = t2.*t4.*t10;
t23 = t4.*t5.*t6;
t24 = t2.*t4.*t11;
t25 = t4.*t6.*t7;
t26 = t13+t14;
t27 = -t23;
t28 = -t25;
t29 = 1.0./t26;
t30 = t16+t20;
t31 = t17+t21;
t32 = t18+t19;
t33 = 1.0./t32;
t34 = t24+t28;
A11 = height_Body.*t4.*t15.*t29.*t31.*6.0-t4.*t8.*t33.*t34.*width_Body.*6.0+t3.*t9.*t15.*t29.*t31.*width_Body.*6.0;
if nargout > 1
    t35 = t22+t27;
    A12 = height_Body.*t4.*t15.*t29.*t30.*6.0-t4.*t8.*t33.*t35.*width_Body.*6.0+t3.*t9.*t15.*t29.*t30.*width_Body.*6.0;
end
if nargout > 2
    A21 = t3.*t6.*t33.*t34.*width_Body.*6.0+height_Body.*t2.*t9.*t15.*t29.*t31.*6.0-t2.*t8.*t9.*t33.*t34.*width_Body.*6.0-t2.*t3.*t4.*t15.*t29.*t31.*width_Body.*6.0;
end
if nargout > 3
    A22 = t3.*t6.*t33.*t35.*width_Body.*6.0+height_Body.*t2.*t9.*t15.*t29.*t30.*6.0-t2.*t8.*t9.*t33.*t35.*width_Body.*6.0-t2.*t3.*t4.*t15.*t29.*t30.*width_Body.*6.0;
end
if nargout > 4
    A31 = t2.*t3.*t33.*t34.*width_Body.*-6.0+height_Body.*t6.*t9.*t15.*t29.*t31.*6.0-t6.*t8.*t9.*t33.*t34.*width_Body.*6.0-t3.*t4.*t6.*t15.*t29.*t31.*width_Body.*6.0;
end
if nargout > 5
    A32 = t2.*t3.*t33.*t35.*width_Body.*-6.0+height_Body.*t6.*t9.*t15.*t29.*t30.*6.0-t6.*t8.*t9.*t33.*t35.*width_Body.*6.0-t3.*t4.*t6.*t15.*t29.*t30.*width_Body.*6.0;
end
